### ISSUE TITLE
Homie support in openhab is buggy?

### ISSUE THREAD

**Issue by michaelfung** [mongoose-os-apps/sonoff-basic-openhab2#2]
Hi Sergio,

Sorry to bother you again. I don't have your email address so I post here.

I am modifying the init.js script to support Homie, but it seems openhab is quite buggy with Homie. I 
am wondering if you have the same issues here:

[[mqtt] Homie $name did not receive](https://github.com/openhab/openhab-addons/issues/6975)

[[mqtt] Homie $retained = false causes channel linking fail](https://github.com/openhab/openhab-addons/issues/7011)

Thanks,
Michael

**Comment by scaprile** [comment]
Hi Michael, I'm reluctant to publish my email here, but it is quite easy; I use the same username in the Giant search engine and cell phone os company mail service.
I only tried OH2.4 and yes, it has some noticeable (and quite annoying) bugs, The binding was supposed to solve them by the next release.
First of all, according to what I've read, if things didn't change, Homie in OH requires retention. That is mandatory. Homie does not strictly enforce it, but most msgs have to be retained, the only things you can not retain are perhaps those that you defined as such; but I didn't have a nice experience with them.
Then, once you've changed anything in the device definitions, you have to remove the old MQTT msgs from the broker (they are, well, retained...). In my experience with 2.4, it was easier to also remove the OH object and create a new one again.
Another annoying topic was that once you restart OH, Homie objects do not work well, they sometimes perform erratically. The solution was to delete them and create them again. Again, this was with 2.4 and the author said most stuff was fixed in dev binding, I could not test it due to limited time and Java compilation resources+expertise.
I seem to remember that release number was also important... anyway, everything that is in the code worked OK on a freshly created object until OH restart; even through device restarts.
This was long ago and I might not remember something or everything correctly, I'm usually in several unrelated projects at the same time and this one was a hobby play "to relax on free time", so I did not document what I could solve or was being fixed.
Best regards.

**Comment by michaelfung** [comment]
Thanks Sergio for your details. I will wait for the next release of the binding.

For power switch,  if $retained is set to true, there is a chance of unexpected power supply which can cause an accident.

Rgds,
Michael

**Comment by scaprile** [comment]
> For power switch, if $retained is set to true, there is a chance of unexpected power supply which can cause an accident.

I wouldn't rely on something like this for anything safety-related. Any switch will resume its last state when re-powered on as soon as it reconnects to the broker. That is expected behavior since otherwise it would lose sync with OH.
However, a properly configured broker will insert a last will message that will instruct OH to properly handle the switch. This would occur some time after connection loss, when MQTT detects it at the broker; so in a shorter disconnection this won't happen.
````
if(Cfg.get('mqtt.will_topic') !== state_topic) {
	Cfg.set({mqtt: {will_topic: state_topic}});
	Cfg.set({mqtt: {will_message: 'lost'}});
	Cfg.set({mqtt: {client_id: client_id}});
	Log.print(Log.INFO, 'MQTT last will has been updated');
};
````
For other purposes I've been playing with sending push-button-like messages using a timed facility of OH. Even though the action is retained, it is forced off after a short while so it effectively is not retained:
````
Switch PB_Switch ["Switchable"] {channel="mqtt:yarayara:button#state",expire="1s,command=OFF"}
````
the _**,expire="1s,command=OFF"**_ part.
IIRC it also needs the **_expire1_** binding.
This works as long as OH remains connected to the broker, which is usually the case on a stable system.

**Comment by michaelfung** [comment]
Agree! I used timestamp and HMAC in another project to protect sensitive operations.

Anyway, you can not rule out someone is naive enough to use this thing to control the launch of ICBM, LOL!
